#!/usr/bin/env python3
"""Print MITRE ATT&CK coverage across all Sigma rules, and optionally export an
ATT&CK Navigator layer.

A one-line answer to the interview question "how do you measure your detection
coverage?": run this, get techniques and rule counts. Add --layer to emit a JSON
file you can load at https://mitre-attack.github.io/attack-navigator/ to SEE the
coverage heat-mapped on the full enterprise matrix, which also makes the gaps
obvious (that is the real point of coverage tracking).

Usage:
    python scripts/attack_coverage.py                # print summary
    python scripts/attack_coverage.py --layer        # also write the layer JSON
    python scripts/attack_coverage.py --layer -o my_layer.json
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

import yaml

RULES_DIR = Path("detections/sigma")
DEFAULT_LAYER_PATH = Path("docs/attack_navigator_layer.json")


def collect_coverage(rules_dir: Path = RULES_DIR) -> dict[str, list[str]]:
    """Map each ATT&CK technique ID to the Sigma rule ids that cover it."""
    coverage: dict[str, list[str]] = defaultdict(list)
    for path in sorted(rules_dir.rglob("*.y*ml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            continue
        rule_id = str(data.get("id", path.stem))
        for technique in data.get("mitre", []):
            coverage[technique].append(rule_id)
    return dict(coverage)


def build_layer(coverage: dict[str, list[str]]) -> dict:
    """Build an ATT&CK Navigator layer (layer format 4.5, enterprise domain).

    Score = number of rules covering the technique, so the Navigator gradient
    shades better-covered techniques darker.
    """
    max_score = max((len(v) for v in coverage.values()), default=1)
    return {
        "name": "BlueForge detection coverage",
        "versions": {"attack": "16", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            "Techniques covered by BlueForge Sigma rules. Score = rule count. "
            "Generated by scripts/attack_coverage.py --layer."
        ),
        "sorting": 3,
        "techniques": [
            {
                "techniqueID": technique,
                "score": len(rule_ids),
                "comment": "Covered by: " + ", ".join(sorted(rule_ids)),
            }
            for technique, rule_ids in sorted(coverage.items())
        ],
        "gradient": {
            "colors": ["#ffe766", "#8ec843"],
            "minValue": 0,
            "maxValue": max_score,
        },
        "legendItems": [{"label": "Covered by at least one BlueForge rule", "color": "#8ec843"}],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layer", action="store_true", help="write an ATT&CK Navigator layer JSON")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_LAYER_PATH,
        help=f"layer output path (default: {DEFAULT_LAYER_PATH})",
    )
    args = parser.parse_args()

    coverage = collect_coverage()
    print(f"Unique techniques covered: {len(coverage)}")
    for technique, rule_ids in sorted(coverage.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        print(f"  {technique}: {len(rule_ids)} rule(s)  [{', '.join(sorted(rule_ids))}]")

    if args.layer:
        layer = build_layer(coverage)
        args.output.write_text(json.dumps(layer, indent=2) + "\n", encoding="utf-8")
        print(f"\nNavigator layer written to {args.output}")
        print("Load it at https://mitre-attack.github.io/attack-navigator/")


if __name__ == "__main__":
    main()
